name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config --global user.name "AzusaHana"
        git config --global user.email "chenyue2330@gmail.com"

    - name: Clean up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /var/lib/mysql
        sudo rm -rf /usr/local/lib/android
        df -h

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 git curl

    - name: Install repo tool
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo

    - name: Initialize repo and sync
      run: |
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        cd $GITHUB_WORKSPACE/kernel_workspace
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8650 -m oneplus12_v.xml --depth=1
        repo sync

    - name: Set up KernelSU
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/msm-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki

    - name: Upload kernel Image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image

   - name: Upload boot
      uses: actions/upload-artifact@v4
      with:
        name: boot
        path: kernel_workspace/kernel_platform/out/msm-kernel-pineapple-gki/dist/boot.img
